<section class="admin__page-section" id="delivery-date-content">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Additional Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div id="delivery-date">
            <strong><?= __('Delivery Date') ?></strong>
            <span><?= $block->getDeliveryDate() ?></span>
        </div>
        <div id="customer-code">
            <strong><?= __('Customer Code') ?></strong>
            <span><?= $block->getCustomerCode() ?></span>
        </div>
        <div id="sap-sent-date">
            <strong><?= __('SAP Sent Date') ?></strong>
            <span><?= $block->getSapSentDate() ?></span>
        </div>
        <div id="sap-sent-status">
            <strong><?= __('SAP Sent Status') ?></strong>
            <span><?= $block->getSapSentStatus() ?></span>
        </div>
        <div id="delivery-comment">
            <strong><?= __('Comment') ?>:</strong>
            <br/>
            <?= $block->getDeliveryComment() ?>
        </div>
    </div>
</section>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $('#delivery-date-content').insertAfter($('.order-view-billing-shipping'));
        }
    );
</script>
