<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="login-container">
    <form class="form password forget"
        action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
        method="post"
        id="form-validate"
        data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
            <div class="field email required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
            </div>
        </div>
    </form>

    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= __('REMEMBERED YOUR PASSWORD') ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?= __('Sign in with your email address.') ?></p>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>" class="action create primary"><span><?= __('SIGN IN') ?></span></a>
                </div>
            </div>
        </div>
    </div>
</div>