<div class="checkout-success">
    <div class="success-title" data-role="title">ORDER CONFIRMED</div>
    <span class="strong thanks">Thanks!</span>
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= $block->escapeHtml(__('Your order # is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
            </br>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
            </br>
        <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <button class="action primary continue green-button-empty" onclick="window.location.href = '<?= $block->escapeUrl($block->getContinueUrl()) ?>';" ><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></button>
        </div>
    </div>
</div>
