<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $total = $block->getItems()->getSize() ?>
<?php if ($total) :?>
    <a href="#" class="action print hidden-print" title="<?= $block->escapeHtmlAttr(__('Print This Page')) ?>">
        <span><?= $block->escapeHtml(__('Print This Page')) ?></span>
    </a>
        <div class="products wrapper grid products-grid">
            <div class="products list items items-catalog displayFlex" id="product-comparison">
                <?php $index = 0; ?>
                <?php $helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $item) :?>
                    <?php $_product = $item; ?>
                    <div class="item-catalog col-md-4 col-s-6 col-12">
                        <div class="product-item-info">
                            <div class="product-item-details">
                                <div class="product-item-info-general">
                                    <strong class="product-item-name">
                                        <a class="product-item-link" title=" <?= $block->escapeHtml($_product->getName()) ?>"
                                            href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                            <?= $block->escapeHtml($_product->getName()) ?>
                                        </a>
                                    </strong>
                                    <p class="product-item-sku">
                                        SKU#: <?= $block->escapeHtmlAttr($_product->getSku()) ?>
                                    </p>
                                    <?php if ($_product->isAvailable()) :?>
                                        <?= $block->getProductDetailsHtml($_product) ?>
                                    <?php endif; ?>

                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                </div>
                                <div class="product-item-info-inner">
                                    <div class="product-item-actions">
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php //phpcs:disable ?>
                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
                                            <?php //phpcs:enable ?>
                                            <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                <img alt="<?= $block->escapeHtml(__('Add to Wish List')) ?>" src="<?php echo $this->getViewFileUrl('images/heart_defualt.svg'); ?>" width="15"/>
                                            </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product-item-photo">
                                <?= $block->getImage($_product, 'product_comparison_list')->toHtml() ?>
                            </a>
                            <div class="product-item-cart desktop">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()) : ?>
                                        <form data-role="tocart-form"
                                            action="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product\Compare::class)->getAddToCartUrl($item)) ?>"
                                            method="post">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div class="displayFlexNoMargin">
                                                <div class="qty-wrapper">
                                                    <div class="qty-controller qty-minus">
                                                        <img src="<?php echo $this->getViewFileUrl('images/minus.svg'); ?>" width="9" alt="substract"/>
                                                    </div>
                                                    <input type="number" name="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo '1' ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" />
                                                    <div class="qty-controller qty-plus">
                                                        <img src="<?php echo $this->getViewFileUrl('images/plus.svg'); ?>" width="9" alt="add"/>
                                                    </div>
                                                </div>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </div>
                                        </form>
                                    <?php else : ?>
                                        <?php if ($_product->getIsSalable()) : ?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="product-item-cart-mobile mobile">
                                <div class="displayFlexNoMargin">
                                    <div class="qty-wrapper">
                                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                    </div>
                                    <div class="cart-wrapper">
                                        <button title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action opentocart" image-bind="<?php echo $this->getViewFileUrl('images/plus_white.svg'); ?>">
                                            <img src="<?php echo $this->getViewFileUrl('images/plus_white.svg'); ?>" width="8" alt="plus"/>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="product-item-cart-quantity mobile">
                                <div class="qty-close">
                                    <img alt="<?= $block->escapeHtml(__('In Wish List')) ?>" src="<?php echo $this->getViewFileUrl('images/close_gray.png'); ?>" height="14"/>
                                </div>
                                <div class="qty-container">
                                    <p><?php echo __('Place in cart')?></p>
                                    <div class="qty-wrapper">
                                        <div class="qty-controller qty-minus">
                                            <img src="<?php echo $this->getViewFileUrl('images/minus.svg'); ?>" width="9" alt="substract"/>
                                        </div>
                                        <input type="number" name="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo '1' ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" />
                                        <div class="qty-controller qty-plus">
                                            <img src="<?php echo $this->getViewFileUrl('images/plus.svg'); ?>" width="9" alt="add"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr/>
                            <div class="product-item-attributes">
                            <?php foreach ($block->getAttributes() as $attribute) :?>
                                <?php if ($block->hasAttributeValueForProducts($attribute)) :?>
                                    <div class="product-item-attribute">
                                        <span class="attribute label">
                                            <strong>
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                            </strong>
                                        </span>
                                        <span class="attribute value">
                                            <?php if (is_string($block->getProductAttributeValue($item, $attribute))) :?>
                                                                <?= /* @noEscape */ $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                            <?php endif; ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                    
                <?php endforeach; ?>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) :?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
        <?php endif; ?>
<?php else :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('You have no items to compare.')) ?></div></div>
<?php endif; ?>
