<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()) : ?>

    <?php if ($block->getUseContainer()) : ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getLastPageNum()>1) : ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?= $block->escapeHtml(__('Page')) ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?= ($block->escapeHtmlAttr($text ? 'link ' : 'action ')) . (!$block->isFirstPage() ? '':'disabled') ?> previous"
                       href="<?= !$block->isFirstPage() ? $block->escapeUrl($block->getPreviousPageUrl()) : '' ?>"
                       title="<?= $block->escapeHtmlAttr($text ? $text : __('Previous')) ?>">
                        <img src="<?php echo $this->getViewFileUrl('images/left_chev.svg'); ?>" alt="Previous" width="6"/>
                    </a>
                </li>

                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?= /* @noEscape */ ($text ? 'link ' : 'action ') . (!$block->isLastPage() ? '':'disabled') ?> next"
                        href="<?= !$block->isLastPage() ? $block->escapeUrl($block->getNextPageUrl()) : '' ?>"   
                        title="<?= $block->escapeHtmlAttr($text ? $text : __('Next')) ?>">
                        <img src="<?php echo $this->getViewFileUrl('images/right_chev.svg'); ?>" alt="Next" width="6"/>
                    </a>
                </li>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->getUseContainer()) : ?>
    </div>
    <?php endif ?>

<?php endif ?>

<script type="text/javascript">
	require([
		'jquery'
	], function ($) {
		"use strict";

		$(document).ready(function(){
			$(document).on('click', '.disabled', function (e) {
                e.preventDefault();
                e.stopImmediatePropagation();
            })
		});

	});
</script>
