<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php $menuClass = $block->getMenu()->getCssClass() ?>

    <div class="<?= $menuClass ?>__mobile">
        <img src="<?php echo $this->getViewFileUrl('images/chev-down.svg'); ?>" alt="more-arrow" width="5px"/>
    </div>

    <nav class="<?= $menuClass ?>">
        <ul class="<?= $menuClass ?>__list">
            <?php foreach ($block->getNodes() as $node): ?>
                <?php
                    $childrenLevel = $node->getLevel() + 1;
                    $children = $this->getNodes($childrenLevel, $node);
                    $node->setIsParent((bool) $children);
                    $parentClass = $children ? ' ' . $menuClass . '__item--parent' : '';
                    $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                    $itemClasses = $parentClass . $additionalClasses;
                ?>
                <li class="<?= $menuClass ?>__item<?= $itemClasses ?>">
                    <?php echo $block->renderMenuNode($node) ?>
                    <?php echo $block->renderSubmenu($children, $node, $childrenLevel) ?>
                </li>
            <?php endforeach ?>
        </ul>
        <div class="<?= $menuClass ?>__mobile-bg"></div>
    </nav>
<?php endif; ?>
