<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
    <div class="block-title filter-title">
        <strong data-role="title" id="open-filter"><img src="<?php echo $this->getViewFileUrl('images/filter.svg'); ?>" alt="shop by" width="20"/></strong>
    </div>
</div>

<script type="text/javascript">
	require([
		'jquery'
	], function ($) {
		"use strict";

		$(document).ready(function(){
			$(document).on('click', '#open-filter', function (e) {
                e.preventDefault();
                e.stopImmediatePropagation();

                $('.sidebar-primary').toggleClass('active');
                $('.page-wrapper').toggleClass('my-filter-active');
                $('body').toggleClass('my-filter-active');
            })
		});

	});
</script>
