<?php 

    $branches = $block->getBranchList();
    $branchesVic = $block->getBranchListVic();
    $branchesNsw = $block->getBranchListNsw();
    $branchesQld = $block->getBranchListQld();
    $branchesSa = $block->getBranchListSa();
    $branchesTas = $block->getBranchListTas();
    $branchesAct = $block->getBranchListAct();
    $branchesWa = $block->getBranchListWa();
    $branchesAuckland = $block->getBranchListAuckland();
?>
<div id="branch-locator">
    <?php if ($block->getApiKey() == "") { ?>
        <div id="no-map">
            <h4><i>Please Add Google maps API Key in the Back-office</i></h4>
        </div>
    <?php } else { ?>
        <div id="map"></div>
        <div id="popup-branch">
            <div id="popup-search">
                <h4>Find your Local Store</h4>
                <input type="text" id="search-branch" placeholder="Enter suburb, city or postcode">
                <span class="search-icon"></span>
                <span id="current-location">Use your current location</span>
                <div id="popup-search-result">

                </div>
            </div>

            <div id="popup-content">

            </div>
            
        </div>
    <?php } ?>

    <div id="branch-container" class="branch-container">
        <h1>Australia</h1>
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Victoria</h4>
            </div>
        </div>

        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesVic as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>New South Wales</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesNsw as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Queensland</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesQld as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>South Australia</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesSa as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Tasmania</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesTas as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>

        
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Australian Capital Territory</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesAct as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>
        
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Western Australia</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesWa as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>
        <br>
        <h1>New Zealand</h1>
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Auckland</h4>
            </div>
        </div>
        <div data-role="content" class="dropdown-content">
            <?php foreach($branchesAuckland as $branch) { ?>
                <div class="branch">
                    <p><strong><?php echo $branch->getName(); ?></strong></p>
                    <p><?php echo $branch->getAddress(); ?></p>
                    <p><?php echo $branch->getCity() . ', '. $branch->getState(). ', ' . $branch->getPostcode(); ?></p>
                    <p>Phone : <?php echo $branch->getPhone(); ?></p>
                    <?php if ($branch->getFax()) { ?>
                        <p><?php echo $branch->getFax(); ?></p>
                    <?php } ?>
                    <a href="" data-id="<?php echo $branch->getId(); ?>" data-lat="<?php echo $branch->getLatitude(); ?>" data-lng="<?php echo $branch->getLongitude(); ?>">SEE MORE</a>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<script>
require([
    'jquery',
    'accordion',
    'https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getApiKey(); ?>',
], function ($) {

    var map;
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -29.9362609, lng: 125.4594216},
            zoom: 4,
            disableDefaultUI: true
        });

    

    <?php foreach($branches as $branch) { ?>
        placeMarker({lat: <?php echo $branch->getLatitude(); ?>, lng:  <?php echo $branch->getLongitude(); ?>}, <?php echo $branch->getId(); ?>)
    <?php } ?>

    function placeMarker(position, id) {
        var logo = {
            url: '<?php echo $block->getLogoSrc() ?>',
            scaledSize: new google.maps.Size(68.5, 27),
        };
        var marker = new google.maps.Marker({
            position: position,
            map: map,
            icon: logo,
            id: id
        });

        marker.addListener('click', function() {
          map.setZoom(13);
          map.setCenter(marker.getPosition());
          setPopupData(marker.id);
        });
        
    }

    $('#search-branch').on('input', function() {
        var value = $(this).val();
        if(value.length > 2) {
            $.ajax({
            url: 'search',
            method: 'POST',
            dataType: 'json',
            data: {query: value},
            }).done(function (branches) {
                var html = "";
                if (branches.length != 0) {
                    $.each(branches, function(key, value){
                        html = html + '<div class="search-result">' +
                        '<h1>'+value.name+'</h1>'+
                        '<p>'+value.address+', '+value.city+', '+value.state+', '+value.postcode+'</p>'+
                        '<a href="#" data-id="'+value.id+'" data-lat="'+value.latitude+'" data-lng="'+value.longitude+'" id="see-infos">SEE INFOS</a></div>';
                    });
                } else {
                    html = "<p style='margin-top: 10px; text-align:center'>No branch found</p>"
                }
                
                $('#popup-search-result').addClass('active').html(html);
            });
        }
    });

    $(document).on('click', '.search-result',function() {
        $(this).children('a')[0].click();
    });

    $(document).on('click', '.search-result a',function(e) {
        e.preventDefault();
        var lat = parseFloat($(this).attr('data-lat'));
        var lng = parseFloat($(this).attr('data-lng'));
        map.setCenter({lat: lat, lng: lng});
        map.setZoom(13);

        setPopupData($(this).attr('data-id'));
    });

    $('#current-location').on('click', function() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                geocoder = new google.maps.Geocoder();
                geocoder.geocode({'latLng': pos}, function(results, status){
                    if (status == google.maps.GeocoderStatus.OK) {
                        var searchAddressComponents = results[0].address_components;
                        $.each(searchAddressComponents, function(){
                            if(this.types[0]=="postal_code"){
                                postcode = this.short_name;
                                $('#search-branch').val(postcode).trigger("input");
                                map.setCenter(pos);
                                map.setZoom(10);
                            }
                        });
                    }
                });

            });
        }

    });

    function setPopupData(id) {

        $.ajax({
            url: 'index',
            method: 'POST',
            dataType: 'json',
            showLoader: true,
            data: {id: id},
            }).done(function (branch) {
                $('#popup-search').css('display', "none");
                $('#popup-content').css('display', 'block').html('');
                var d = new Date();

                var fax = "";
                if(branch.fax != undefined) {
                    fax = '<p>Fax: '+branch.fax+'</p>';
                }

                var html = '<span class="close"></span>' +
                '<h1>'+branch.name+'</h1>'+
                '<p>'+branch.address+', '+branch.city+', '+branch.state+', '+branch.postcode+'</p>'+
                '<p>Phone: '+branch.phone+'</p>' +
                fax +
                '<h4>OPENING HOURS</h4>' +
                '<table>'+ 
                '<tr><td>Today</td><td>'+ getDayMonth(d, d.getDay()) +'</td><td>'+matchDay(d.getDay(), branch)+'</td></tr>'+
                '<tr><td>'+ getDayOfTheWeek((d.getDay() +1) % 7)+'</td><td>'+ getDayMonth(d, 1) +'</td><td>'+matchDay((d.getDay() +1) % 7, branch)+'</td></tr>'+
                '<tr><td>'+ getDayOfTheWeek((d.getDay() +2) % 7)+'</td><td>'+ getDayMonth(d, 2) +'</td><td>'+matchDay((d.getDay() +2) % 7, branch)+'</td></tr>'+
                '<tr><td>'+ getDayOfTheWeek((d.getDay() +3) % 7)+'</td><td>'+ getDayMonth(d, 3) +'</td><td>'+matchDay((d.getDay() +3) % 7, branch)+'</td></tr>'+
                '<tr><td>'+ getDayOfTheWeek((d.getDay() +4) % 7)+'</td><td>'+ getDayMonth(d, 4) +'</td><td>'+matchDay((d.getDay() +4) % 7, branch)+'</td></tr>'+
                '<tr><td>'+ getDayOfTheWeek((d.getDay() +5) % 7)+'</td><td>'+ getDayMonth(d, 5) +'</td><td>'+matchDay((d.getDay() +5) % 7, branch)+'</td></tr>'+
                '<tr><td>'+ getDayOfTheWeek((d.getDay() +6) % 7)+'</td><td>'+ getDayMonth(d, 6) +'</td><td>'+matchDay((d.getDay() +6) % 7, branch)+'</td></tr>'+
                '</table>'+
                '<a href="#" id="find-another">FIND ANOTHER STORE</a>';

                $('#popup-content').addClass('active').html(html);
        });
    }

    function getDayMonth(d, i) {

        var dd = String(d.getDate() + i).padStart(2, '0');
        
        const monthNames = ["January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        ];
        var mm = String(monthNames[d.getMonth()]); 
        
        return dd + ' ' + mm;
    }

    function getDayOfTheWeek(i) {
        var days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        var dayName = days[i];
        
        return dayName;
    }

    function matchDay(i, branch) {
        var dayMatch = {
            0: branch.sunday, 
            1: branch.monday,
            2: branch.tuesday,
            3: branch.wednesday,
            4: branch.thursday,
            5: branch.friday,
            6: branch.saturday
        }

        var day = dayMatch[i];

        return day;
    }

    $(document).on('click', '#find-another',function (e) {
        $('html, body').animate({
            scrollTop: $("#branch-container").offset().top + 500
        }, 500);

        $('#popup-search').css('display', 'block');
        $('#popup-content').css('display', 'none').html('');
        $('#popup-branch').removeClass('active');
    });

    $(document).on('click', '.close',function (e) {
        e.preventDefault();
        $('#popup-search').css('display', 'block');
        $('#popup-content').css('display', 'none').html('');
        $('#popup-branch').removeClass('active');
    });

    $(".branch-container").accordion({ 
        collapsible: true,
        multipleCollapsible: true,
        icons: {"header": "caret-right", "activeHeader": "caret-down"},
        animate: {duration:500,easing:"easeOutCubic"}
    });

    $('.branch a').on('click', function(e) {
        e.preventDefault();
        var lat = parseFloat($(this).attr('data-lat'));
        var lng = parseFloat($(this).attr('data-lng'));
        map.setCenter({lat: lat, lng: lng});
        map.setZoom(13);
        $('html, body').animate({
            scrollTop: $("#maincontent").offset().top
        }, 500)

        setPopupData($(this).attr('data-id'));
    });
});
</script>