<?php $news = $block->getAllNews(); ?>

<div id="all-news-container">
    <div class="news-container">
    <?php $i = 0; ?>
        <?php foreach($news as $new) { ?>
            <a <?php if($i % 3 == 0 ) { ?>style="margin-left: 0"<?php } ?>href="<?php echo $block->getUrl('latestnews/news/view/').$new->getUrlKey(); ?>" class="news">
                <div class="img" style='background-image: url("<?php echo $block->getMediaBaseUrl($new->getImage()); ?>")'></div>
                <div class="news-content">
                    <h4><?php echo $new->getTitle(); ?></h4>
                    <p class="date"><?php echo $block->formatDateNews($new->getCreatedAt()); ?></p>
                    <?php echo substr($new->getShortContent(), 0 , 250); ?>
                    ...
                </div>
            </a>
            <?php 
                $i++;
            ?>
        <?php } ?>
    </div>
     <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar-products toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
</div>